#[build]
#  command = "nx build web --prod --aot && npx scully --scan"
#  publish = "dist/static"

[[redirects]]
  from = "/contact"
  to = "/"
  status = 301

[[redirects]]
  from = "https://blog.benjamincharity.com/*"
  to = "https://www.benjamincharity.com/articles/:splat"
  status = 301
