export const COMPANIES: ReadonlyArray<string> = [
  'Alternative Apparel',
  'Baker Hughes',
  'Case-Mate',
  'InComm',
  'Kenzie Lane Innovation',
  'Lamar Advertising Company',
  'NBA',
  'NCAA',
  'NCR',
  'NFL',
  'Showcase IDX',
  'Terminus Software',
  'The Home Depot',
  'Tourbuzz',
  'Turner Broadcasting System',
];
